length: [5000,2500,1000,500,350]
species: ['vih']
param:
  minimap2: {
    name: ['default'],
    command: ['-ax#map-ont']}
  mm2f: {
    name: ['default'],
    command: ['-ax#map-ont']}
  graphmap2: {
    name: ['default'],
    command: ['align#-a#sg#--auto-rebuild-index#']}
  graphmap: {
    name: ['default'],
    command: ['align#-x#sensitive']}
  blasr: {
    name: ['default'],
    command: ['--sam']}
  winnowmap: {
    name: ['default'],
    command: ['-ax#map-ont']}
  magicblast: {
    name: ['default'],
    command: ['-splice#F']}
  lra: {
    name: ['default'],
    command: ['-t#16']}