dataset: data/samples/convert_read.fasta
ref: data/sequence.fasta
param:
  minimap2: {
    name: ['default'],
    command: ['-ax#map-ont']}
  mm2f: {
    name: ['default'],
    command: ['-ax#map-ont']}
  graphmap2: {
    name: ['default'],
    command: ['align#-a#sggotoh']}
  graphmap: {
    name: ['default'],
    command: ['align#-x#sensitive']}
  blasr: {
    name: ['default'],
    command: ['--sam']}
  #stampy: {
  #  name: ['default'],
  #  command: ['#']}
  #minimap: {
  #  name: ['default'],
  #  command: ['#']}
