realdata: False
length: [500,7500]
species: ['covid']
error_rate: ['0.95']
model: 'R103'
model_m: 'r103'
cig_modif: False
param:
  minimap2: {
    name: ['default','big','small'],
    command: ['#','-k#12#-w#4','-k#7#-w#5']}
  minimap2old: {
    name: ['default','big','small'],
    command: ['#','-k#12#-w#4','-k#7#-w#5']}
  graphmap: {
    name: ['default','A1','A2'],
    command: ['#','-k#7#-A#8','-k#5#-A#7#--freq-percentile#1.0']}
  blasr: {
    name: ['default*','G1','G2'],
    command: ['#','--minMatch#7#--nCandidates#20','--minMatch#10#--nCandidates#20',]}
  winnowmap2: {
    name: ['default*','D1','D2'],
    command: ['#','-k#15#-w#1','-k#12#-w#4']}
  magicblast: {
    name: ['default*','F1','F2'],
    command: ['-splice#F','-splice#F##-word§size#16','-splice#F#-word§size#22#']}
  lra: {
    name: ['default','E1','E2*','E3','E4','E5','E6'],
    command: ['#','-W#4#-K#12','-K#7#-W#5']}
  blend: {
    name: ['default*','J1*','J2','J3','J4','J5','J6'],
    command: ['#','-k#7#-w#5#--fixed-bits=24#--neighbors=8','-k#12#-w#4#--fixed-bits=30#--neighbors=10']}
  bwamem: {
    name: ['default','J1*','J2'],
    command: ['#','-k#7#-W#10','-k#5#-w#1']}
  syncminimap: {
    name: ['default*','I1','I2','I3','I4','I5','I6'],
    command: ['-k#15#-w#10#--downsample#1#--s-mer#5#--pos1#3#--pos2#9','-k#7#-w#10#--downsample#1#--s-mer#5#--pos1#3#--pos2#9','-k#5#-w#1#--downsample#1#--s-mer#5#--pos1#3#--pos2#9']}

contamination: 10 #20% de read humain
seed : 12345

number : 100

variant: { 
  number: 1,
  specify: [20],
  taux: [99]}
#for specifie type of snp {'i':['0r'],'d':['0r'],'s':['1r']} else type 
#number variant will be number/1000 variation