import random

NUC=["A","T","C","G"]
vir="GACTATGGTTGCACCAGACCCTCCACAGATCTCTATGTTCCCAAACCGTTTCCGGATTGTATTAAAGAAGTTTGATTAATTGGAGTTGTACGAATATTAG"
P1="CAAATAGCATGAGTTACGCTCAAGTTAAACTGCTGATAGTTATCCAGTTGAGACTATCTTACTTGCTAATGTGTTCCTCTCCCTAGGGCTATTGGGGGTG"
P2="TTACATGAAAAGACAATATGGGCGAGACTACTATAGAGACCGGGCAAAATCGGTCCGAGGTCGCTCAAATCCCTTCTACTGCGCACCGTGTGTAGCTCCA"
def one_file(x):
    f1=open("échantillon_"+x+".txt","w")
    for i in range(500):
        seq=[]
        for y in range(100):
            seq.append(NUC[random.randint(0,3)])
        seq="".join(seq)
        f1.write(seq+"\n")
            
one_file("2")